language: csharp
solution: TestSonarCloud.sln

dist: trusty

addons:
  sonarcloud:
    organization: "arturbabaev"
    token:
      secure: "e642b14c6d6adbcd5457f93a280910135810ad84" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
